### ISSUE TITLE
Put the MHF full-color globe logo and accompanying text into the footer

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/laptopsforfamilies.org#20]
In the left part of the footer:
<img width="342" alt=" 2021-10-04 at 10 18 56" src="https://user-images.githubusercontent.com/74739/135895554-7d4a4b8e-d3ec-4a38-870a-e4fd2f9f84b0.png">

- [ ] Put in a small version of the MHF full-color globe logo from [media-kit](https://github.com/margaritahumanitarian/media-kit), perhaps the [64x64 file](https://github.com/margaritahumanitarian/media-kit/blob/main/logo-full-color/MHF-Color64.png)
  - [ ] Copy it into this repo
  - [ ] Show it in the footer with an `<img>` tag
  - [ ] Check that the footer looks good at different resolutions after this change (mobile, tablet, desktop browser sizes)
- [ ] Add the accompanying text: Laptops for Families is a project organized by Margarita Humanitarian Foundation, a 501c3 public charity in the United States.
- [ ] Replace or remove the airplane and the word `LANDING` if the footer would look better without it. Experiment and play around with what you think looks good.

**Comment by akshitarora921** [comment]
Hi, Can I work on this?
